### PR TITLE
ci: install ninja via pip

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by Cogitri** [comment]
By installing ninja via pip we should avoid this breaking again.

**Comment by Cogitri** [comment]
Hm, I don't really get why it doesn't just run `dub build` for the one macOS build with dmd-2.085.1

**Comment by s-ludwig** [comment]
What about checking `TRAVIS_OS_NAME` in `travis.sh` instead? I think `include` just adds the same configuration as an additional job without overwriting the original one.

**Comment by Cogitri** [comment]
Right, that'd work

**Comment by Cogitri** [comment]
Seems to work now :)

**Comment by Cogitri** [comment]
Ah nevermind, SH trolled me ^^

**Comment by Cogitri** [comment]
Works now (for good)

**Comment by s-ludwig** [comment]
Sorry, I missed this earlier (I'm not really able to keep up with github notifications at the moment). I'll tag a new release (including the meson.build version bump).

**Comment by Cogitri** [comment]
Ah, no worries. Thanks for tagging a new release :)

**Pull request merged**
